[package]
name = "TaskWeb"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.3.0"
axum = "0.6.20"
dotenv = "0.15.0"
serde = "1.0.188"
serde_json = "1.0.1"
tokio = { version = "1.32.0", features = ["full"] }